export const projects = [
  {
    // title: 'MERN Memories',
    // description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    //   image: '/images/1.png',
    //   tags: ['Mongo', 'Express', 'React', 'Node'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 0,
    title: 'Meta-Evil',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/MetaEvil1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/seanking8',
    visit: 'https://chickon98.itch.io/metaevil',
    id: 0,
  },
  {
    // title: 'E-Commerce',
    // description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    // image: '/images/2.png',
    // tags: ['React', 'JavaScript'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 1,
    title: 'Arena VR',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/Arena_2.png',
    tags: ['c#', 'Unity'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    // title: 'WebRTC App',
    // description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    //   image: '/images/3.jpg',
    //   tags: ['React', 'WebRTC'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 2,
    title: 'IRL Vintage',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/IRLV_2.png',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    // title: 'Unichat',
    // description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    // image: '/images/4.jpg',
    // tags: ['React', 'ChatEngine', 'Firebase'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 3,
    title: 'CountrFit Clothing',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/CFC_2.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    // title: 'Unichat',
    // description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    // image: '/images/4.jpg',
    // tags: ['React', 'ChatEngine', 'Firebase'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 3,
    title: 'Flood - FPS Game',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/Flood_1.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    // title: 'E-Commerce',
    // description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    // image: '/images/2.png',
    // tags: ['React', 'JavaScript'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 1,
    title: 'MindYou',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/MY_1.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  }
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey with simple HTML/CSS pages and Java apps', },
  { year: 2019, text: 'Added JS functionality. Delved into SQL and DB management', },
  { year: 2020, text: 'Began my game dev journey using Unity and C#. Designed more appealing webpages', },
  { year: 2021, text: 'Implemented MERN stack and RESTful APIs to create polished full-stack projects', },
  { year: 2022, text: 'Launched 3 PC games for public download. Used Selenium and WebDriver for automated testing', },
];