export const projects = [
  {
    // title: 'Unichat',
    // description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    // image: '/images/4.jpg',
    // tags: ['React', 'ChatEngine', 'Firebase'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 3,
    title: 'Flood - FPS Game',
    description: "This full-stack solution was built as a place to sell second-hand clothing. It's secure password database allowed users to login safely and find the items they were previously interested in saved to their shopping cart.",
    image: '/images/Flood_1.png',
    tags: ['C#', 'Unity', 'Blender'],
    source: 'https://github.com/seanking8/Flood_FPS_Game',
    visit: 'https://seankingdev.itch.io/flood',
    id: 4,
  },
  {
    // title: 'WebRTC App',
    // description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    //   image: '/images/3.jpg',
    //   tags: ['React', 'WebRTC'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 2,
    title: 'IRL Vintage',
    description: "This full-stack solution was built as a place to sell second-hand clothing. It's secure password database allowed users to login safely and find the items they were previously interested in saved to their shopping cart.",
    image: '/images/IRLV_2.png',
    tags: ['JS', 'PHP', 'MySQL', 'AWS'],
    source: 'https://github.com/seanking8/IRLVintage',
    visit: '/',
    id: 2,
  },
  {
    // title: 'MERN Memories',
    // description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    //   image: '/images/1.png',
    //   tags: ['Mongo', 'Express', 'React', 'Node'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 0,
    title: 'Meta-Evil',
    description: "This full-stack solution was built as a place to sell second-hand clothing. It's secure password database allowed users to login safely and find the items they were previously interested in saved to their shopping cart.",
    image: '/images/MetaEvil1.png',
    tags: ['C#', 'Unity', 'Blender'],
    source: 'https://github.com/seanking8/MetaEvil',
    visit: 'https://seankingdev.itch.io/meta-evil',
    id: 0,
  },
  {
    // title: 'E-Commerce',
    // description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    // image: '/images/2.png',
    // tags: ['React', 'JavaScript'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 1,
    title: 'MindYou',
    description: "This full-stack solution was built as a place to sell second-hand clothing. It's secure password database allowed users to login safely and find the items they were previously interested in saved to their shopping cart.",
    image: '/images/MY_1.png',
    tags: ['Java', 'Android Studio'],
    source: '/',
    visit: '/',
    id: 5,
  },
  {
    // title: 'E-Commerce',
    // description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    // image: '/images/2.png',
    // tags: ['React', 'JavaScript'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 1,
    title: 'Arena VR',
    description: "This full-stack solution was built as a place to sell second-hand clothing. It's secure password database allowed users to login safely and find the items they were previously interested in saved to their shopping cart.",
    image: '/images/Arena_2.png',
    tags: ['C#', 'Unity', 'XR Toolkit'],
    source: 'https://github.com/seanking8/The_Arena_VR_Game',
    visit: 'https://seankingdev.itch.io/arena',
    id: 1,
  },
  {
    // title: 'Unichat',
    // description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    // image: '/images/4.jpg',
    // tags: ['React', 'ChatEngine', 'Firebase'],
    // source: 'https://google.com',
    // visit: 'https://google.com',
    // id: 3,
    title: 'CountrFit Clothing',
    description: "This full-stack solution was built as a place to sell second-hand clothing. It's secure password database allowed users to login safely and find the items they were previously interested in saved to their shopping cart.",
    image: '/images/CFC_2.png',
    tags: ['HTML5', 'CSS', 'JS'],
    source: 'https://github.com/seanking8/CountrFitClothing',
    visit: '/',
    id: 3,
  }
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey with simple HTML/CSS pages and Java apps', },
  { year: 2019, text: 'Added JS functionality. Delved into SQL and DB management', },
  { year: 2020, text: 'Began my game dev journey using Unity and C#. Designed more appealing webpages', },
  { year: 2021, text: 'Implemented MERN stack and RESTful APIs to create polished full-stack projects', },
  { year: 2022, text: 'Launched 3 PC games for public download. Used Selenium and WebDriver for automated testing', },
];